### ISSUE TITLE
opam lint complaints

### ISSUE THREAD

**Issue by mmottl** [ocaml/oasis2opam#13]
`opam lint` complains about several issues on files generated by `oasis2opam`.  E.g. with Lacaml:
```
Validation failed for ~/archive/github/mmottl/forked/opam-repository/packages/lacaml/lacaml.7.2.1/opam:
  - Field 'ocaml-version' is deprecated, use 'available' instead
  - Missing field 'bug-reports'
  - Package declares 'depexts', but has no 'post-messages' to help the user out when they are missing
```

**Comment by Chris00** [comment]
For `bug-reports`, see https://github.com/ocaml/oasis/pull/62
I will add some heuristics when `Homepage` is Github.

**Comment by Chris00** [comment]
Not sure what you do expect for the `depexts` message.  `depexts` cannot be inferred from the `_oasis` file anyway so must be added to `_opam`.  I think the message should be there too — something like:
```
post-messages: [
  "Could not build Lacaml. Note the development version of LAPACK should be installed on your system." {failure}
]
```

**Comment by mmottl** [comment]
I agree, the post-messages field should go into _opam.  I'll eventually take a look at this.

**Comment by mmottl** [comment]
Thanks!

**Comment by Chris00** [comment]
Do you need a new release?

**Comment by mmottl** [comment]
Thanks, no new release necessary, it's only a minor issue.

**Comment by mmottl** [comment]
@Chris00 Is there a new release in the pipeline?  It seems the OPAM team is now adding automated checks with opam lint, and I got an email with errors + warnings about the currently generated OPAM files.  Not super-urgent, though, the system apparently still accepts the package if it compiles.

**Comment by Chris00** [comment]
@mmottl I just finished a couple of improvements.  I think the state is ready for a new release.  Do you have remarks on the current Git version (more testing is good! `;-)`)?  I'm also waiting for @agarwal to see whether he as some remarks for [oloop](https://github.com/ocaml/oloop/issues/35).

**Comment by mmottl** [comment]
@Chris00 Thanks a lot for your work on this!  I've just tested your current GitHub branch, and it seems to address all my issues (at least for Lacaml).  I'd be happy to see it released.

**Comment by Chris00** [comment]
[Release pending](https://github.com/ocaml/opam-repository/pull/4386).
