### ISSUE TITLE
depopts support

### ISSUE THREAD

**Issue by edwintorok** [ocaml/oasis2opam#14]
Running oasis2opam on [debian-formats](http://anonscm.debian.org/cgit/pkg-ocaml-maint/packages/ocaml-debian-formats.git/) generates this version constraint which is not satisfiable on OCaml 4.01+: `("mikmatch" {= "1.0.6"} | "mikmatch" {= "1.0.5"})`

However the original _oasis file didn't have a version constraint, apparently this is because versions higher than `1.0.6` of mikmatch have `pcre` as a depopts, so I think that `oasis2opam` should in this case generate this: `"mikmatch" "pcre"`

```
$ oasis2opam --query mikmatch_pcre
"mikmatch_pcre" is provided by: ("mikmatch" {= "1.0.6"} | "mikmatch" {= "1.0.5"})
$ opam install mikmatch.1.0.6
[ERROR] mikmatch.1.0.6 is not available because it requires OCaml >= 4.00 & < 4.01.
$ opam install mikmatch.1.0.5
[ERROR] mikmatch.1.0.5 is not available because it requires OCaml < 4.01.
$ opam info mikmatch
             package: mikmatch
             version: 1.0.8
          repository: default
        upstream-url: https://github.com/mjambon/mikmatch/archive/v1.0.8.tar.gz
       upstream-kind: http
   upstream-checksum: 0f3b272491bff4fe842948dbf71d022e
            homepage: http://mjambon.com/micmatch.html
                 doc: http://mjambon.com/mikmatch-manual.html
             depends: ocamlfind & camlp4 & tophide >= 1.0.2
             depopts: pcre
   installed-version: 1.0.8 [system 4.02.1 4.02.0+trunk]
  available-versions: 1.0.5, 1.0.6, 1.0.7, 1.0.8
         description: OCaml syntax extension for regexps

Workaround:
```
oasis2opam --local
sed -i -e 's/("mikmatch".*/("mikmatch" "pcre")/' opam/opam
```

**Comment by Chris00** [comment]
This has nothing to do with depext.  This is because there is no way to detect what ocamlfind libraries the opam package mikmatch is providing.  In the versions above

    "ocamlfind" "remove" "mikmatch_pcre"

was used as the remove instructions but not in later ones.  The solution is to add a `findlib` file to `mikmatch` listing the ocamlfind packages (one per line).  @mjambon ?

**Comment by edwintorok** [comment]
I tried creating a `findlib` file containing this, but that only  fixes the version constraints, it doesn't add `pcre` to the dependencies:
```
mikmatch_pcre
mikmatch_str
```

Mikmatch only installs mikmatch_pcre findlib library if the optional build-dependency pcre is available, but how do I express this in findlib, or some other opam metadata so thyat `oasis2opam` can pick it up?

**Comment by Chris00** [comment]
> Mikmatch only installs mikmatch_pcre findlib library if the optional build-dependency pcre is available

This means that your project should depend on `mikmatch` **and** `pcre`.

**Comment by edwintorok** [comment]
On 06/08/2015 06:17 PM, Christophe Troestler wrote:
>     Mikmatch only installs mikmatch_pcre findlib library if the optional build-dependency pcre is available
> 
> This means that your project should depend on |mikmatch| *and* |pcre|.

In the generated opam yes, but how do I tell oasis2opam that mikmatch_pcre should be turned into mikmatch+pcre on opam side?
I could add mikmatch_pcre, pcre to the _oasis file of the project, is that what you meant?
https://github.com/gildor478/ocaml-debian-formats/blob/master/_oasis

**Comment by Chris00** [comment]
On Mon, 8 Jun 2015 08:23:12 -0700, Török Edwin wrote:
> 
> On 06/08/2015 06:17 PM, Christophe Troestler wrote:
> > Mikmatch only installs mikmatch_pcre findlib library if the optional
> build-dependency pcre is available
> >
> > This means that your project should depend on |mikmatch| *and* |pcre|.
> 
> In the generated opam yes, but how do I tell oasis2opam that mikmatch_pcre should be turned into mikmatch+pcre on opam side?

There is no reliable way for oasis2opam to know that mikmatch_pcre requires an optional dependency on PCRE.

> I could add mikmatch_pcre, pcre to the _oasis file of the project, is that what you meant?

Yes.

**Comment by Chris00** [comment]
Assuming you are happy with the above solution.
