### ISSUE TITLE
.install file should contain more than just bins section

### ISSUE THREAD

**Issue by edwintorok** [ocaml/oasis2opam#17]
`opam lint` warns that there is no `remove` field when `_oasis` only builds an executable:
  warning 27: No field 'remove' while a field 'install' is present, uncomplete uninstallation suspected

I thought that in this case the `install` field could be removed too and just rely on the generated `.install` file, however that file only contains the `bin` section.
For example [for this _oasis file](http://gitweb.skylable.com/gitweb/?p=libres3.git;a=blob_plain;f=libres3/_oasis;hb=HEAD) `oasis2opam --local` doesn't generate the `sbin`,`etc` or `doc` sections in the `.install` file:

```diff
-sbin: [
-  "libres3/_build/src/server/libres3_setup.native" {"libres3_setup"}
-  "libres3/_build/src/server/libres3_report.native" {"libres3_report"}
-  "libres3/_build/src/ocsigen/libres3_ocsigen.native" {"libres3_ocsigen"}
-  "libres3/src/files/sbin/libres3_certgen"
-  "libres3/src/files/sbin/libres3"
-  "libres3/src/files/sbin/libres3_env.sh"
-]
-etc: [
-  "libres3/src/files/conf/libres3.sample.s3cfg"
-  "libres3/src/files/conf/libres3-insecure.sample.s3cfg"
-  "libres3/src/files/conf/mime.types"
-]
-doc: [
-  "libres3/README"
-  "libres3/src/files/s3genlink.py"
-  "libres3/doc/manual/manual.pdf"
+bin: [
+  "?_build/src/server/libres3_report.byte" {"libres3_report"}
+  "?_build/src/server/libres3_report.native" {"libres3_report"}
+  "?_build/src/server/libres3_setup.byte" {"libres3_setup"}
+  "?_build/src/server/libres3_setup.native" {"libres3_setup"}
+  "?_build/src/ocsigen/libres3_ocsigen.byte" {"libres3_ocsigen"}
+  "?_build/src/ocsigen/libres3_ocsigen.native" {"libres3_ocsigen"}
```

**Comment by Chris00** [comment]
As suggested, I now only add an `install` field [if libraries need to be installed](https://github.com/ocaml/oasis2opam/commit/331b46562c3d72276e0265b891f85bc39ceb96cd).

**Comment by Chris00** [comment]
About the files in green, I do not see how one could guess that they should be in `sbin`.  I am not sure which convention could be adopted.  Maybe is the `Path` contains `sbin` as one of its components??

**Comment by edwintorok** [comment]
Thanks for the update.

The `DataFiles` field uses `$docdir`, `$sysconfdir` and `$sbindir` in `_oasis`, so supporting the `DataFiles` field and detecting standard substitution variables would solve the problem of having
all the files that oasis would install present in the generated opam `.install` file, which is what this bug is mostly about.

Oasis itself doesn't support choosing between `bindir` and `sbindir` either, and I think that distinction is quite rare (in fact my application is the only one using it currently in opam), so I'm fine if I have to manually adjust that outside of `oasis2opam`.

**Comment by Chris00** [comment]
I am a bit surprised by the prefix `libres3` to all your paths.  Is it really needed?

**Comment by edwintorok** [comment]
Probably not needed for the doc and etc files.
I'm not very good at naming, and just wanted to ensure I don't conflict with something else with my binaries, and then I just applied that convention to all files I install (`LibreS3` is the application's name)

**Comment by Chris00** [comment]
I had a look to https://github.com/sx-mirror/libres3 and it comes from the fact that `_oasis` is not in the toplevel directory of your project/tarball (it should be).  The paths that `oasis2opam` will generate assume that.  Later one can maybe add options such as `--bindir`, `--sbindir`,...

**Comment by Chris00** [comment]
Any reason why files such as `../files/info.log ($localstatedir/log/libres3/),` are not present in the above list?

**Comment by edwintorok** [comment]
Sorry about the confusion, I run `oasis2opam --local` from the `libres3/` subdir (please ignore whats in the root, it is not meant for oasis or opam):
```
$ git clone http://git.skylable.com/libres3 && cd libres3/libres3
$ oasis2opam --local
$ cat opam/files/libres3.install
```

`info.log`: its a dummy file used to create a directory, comes in handy for `.deb` and `.rpm`, not really needed for opam as libres3 will create the needed directories on startup. it can be in the .install though.

**Comment by Chris00** [comment]
>  I run oasis2opam --local from the libres3/ 

But then there should be no `libres3/` prefix, right?

**Comment by edwintorok** [comment]
right, opam's .install file has a `libres3/` prefix because it runs from toplevel. I should really clean up this build system of mine ... :)

**Comment by Chris00** [comment]
The current implementation (not yet pushed) generates:
```
bin: [
  "?_build/src/server/libres3_report.byte" {"libres3_report"}
  "?_build/src/server/libres3_report.native" {"libres3_report"}
  "?_build/src/server/libres3_setup.byte" {"libres3_setup"}
  "?_build/src/server/libres3_setup.native" {"libres3_setup"}
  "?_build/src/ocsigen/libres3_ocsigen.byte" {"libres3_ocsigen"}
  "?_build/src/ocsigen/libres3_ocsigen.native" {"libres3_ocsigen"}
]
sbin: [
  "src/ocsigen/../files/sbin/libres3_env.sh"
  "src/ocsigen/../files/sbin/libres3"
  "src/ocsigen/../files/sbin/libres3_certgen"
]
share: [
  "src/ocsigen/../files/info.log"
]
etc: [
  "src/ocsigen/../files/conf/libres3.sample.s3cfg"
  "src/ocsigen/../files/conf/libres3-insecure.sample.s3cfg"
  "src/ocsigen/../files/conf/mime.types"
]
doc: [
  "src/ocsigen/../files/conf/logrotate.d/libres3" {"logrotate.d/libres3"}
  "src/ocsigen/../files/s3genlink.py"
  "src/ocsigen/../../README"
  "src/ocsigen/../../COPYING"
  "src/ocsigen/../../doc/manual/manual.pdf"
]
```
Is that OK for you?  Any remarks?

**Comment by edwintorok** [comment]
On 4 July 2015 01:05:02 EEST, Christophe Troestler <notifications@github.com> wrote:
>The current implementation (not yet pushed) generates:
>```
>bin: [
>  "?_build/src/server/libres3_report.byte" {"libres3_report"}
>  "?_build/src/server/libres3_report.native" {"libres3_report"}
>  "?_build/src/server/libres3_setup.byte" {"libres3_setup"}
>  "?_build/src/server/libres3_setup.native" {"libres3_setup"}
>  "?_build/src/ocsigen/libres3_ocsigen.byte" {"libres3_ocsigen"}
>  "?_build/src/ocsigen/libres3_ocsigen.native" {"libres3_ocsigen"}
>]
>sbin: [
>  "src/ocsigen/../files/sbin/libres3_env.sh"
>  "src/ocsigen/../files/sbin/libres3"
>  "src/ocsigen/../files/sbin/libres3_certgen"
>]
>share: [
>  "src/ocsigen/../files/info.log"
>]
>etc: [
>  "src/ocsigen/../files/conf/libres3.sample.s3cfg"
>  "src/ocsigen/../files/conf/libres3-insecure.sample.s3cfg"
>  "src/ocsigen/../files/conf/mime.types"
>]
>doc: [
>"src/ocsigen/../files/conf/logrotate.d/libres3" {"logrotate.d/libres3"}
>  "src/ocsigen/../files/s3genlink.py"
>  "src/ocsigen/../../README"
>  "src/ocsigen/../../COPYING"
>  "src/ocsigen/../../doc/manual/manual.pdf"
>]
>```
>Is that OK for you?  Any remarks?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/ocaml/oasis2opam/issues/17#issuecomment-118432664

Now I notice the double entries for `.byte` and `.native`, will opam handle that by having the native one take precedence? The rest looks good, thanks a lot! Will test the install file when I'm in front of my computer again later today.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Chris00** [comment]
> double entries for `.byte` and `.native`, will opam handle that by having the native one take precedence? 

To make sure, [I asked](https://github.com/ocaml/opam/issues/2242).  Note that, ideally, oasis would generate an install file (through a plugin) but this has to be written yet.

**Comment by edwintorok** [comment]
On 4 July 2015 10:44:19 EEST, Christophe Troestler <notifications@github.com> wrote:
>> double entries for `.byte` and `.native`, will opam handle that by
>having the native one take precedence? 
>
>To make sure, [I asked](https://github.com/ocaml/opam/issues/2242). 
>Note that, ideally, oasis would generate an install file (through a
>plugin) but this has to be written yet.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/ocaml/oasis2opam/issues/17#issuecomment-118479748

In my specific case I could use CompiledObject: Best to tell oasis to build only one of them, but yeah in general such a plugin would be useful.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Chris00** [comment]
I opened a [feature request](https://forge.ocamlcore.org/tracker/index.php?func=detail&aid=1470&group_id=54&atid=294).  I do not think oasis2opam can do much more, so closing.

**Comment by edwintorok** [comment]
Thanks, the `.install` looks good.

**Comment by Chris00** [comment]
BTW, when only executables are built, all dependencies are now declared `{build}`.
