### ISSUE TITLE
depopts are not quoted in master

### ISSUE THREAD

**Issue by seliopou** [ocaml/oasis2opam#23]
While testing #22 I came across a bug where depopts are no longer being quoted. Where as previously they would be generated like this:

```
depopts: [
  "js_of_ocaml"
]
```
they are now being generated like this:
```
depopts: [
  js_of_ocaml
]
```
513bdbe7d93b97eba14699975d14f9de49ae86f0 seems to be the culprit.

**Comment by Chris00** [comment]
Right. Fixed in baec97a
