### ISSUE TITLE
ocamlbuild should be listed as a build dependency when ocamlbuild is the build tool

### ISSUE THREAD

**Issue by hcarty** [ocaml/oasis2opam#25]
Now that there is an ocamlbuild package in opam it should be listed in the generated opam file.

**Comment by mmottl** [comment]
I've just received a request from the OPAM developers to update my packages wrt. that problem.  It's not super-urgent, because they patched my OPAM files in their repository.  But it would be nice to see a fix soon so I don't have to manually change generated OPAM files for future releases.

**Comment by hcarty** [comment]
It looks like this is fixed in the latest master branch.  After running `opam pin add oasis2opam --dev-repo` I can run `oasis2opam --local` and have `ocamlbuild` listed as a build dependency.

Could you make a new release with this included?

**Comment by Chris00** [comment]
This has also been requested by @mmottl — https://github.com/ocaml/opam-repository/pull/6183#issuecomment-205442289
I'd like to include a fix for the `files` section in this release too — https://github.com/ocaml/opam-repository/pull/6183#issuecomment-205442289  If I see I do not have the time to do it in the coming days, I'll release it as is.

**Comment by hcarty** [comment]
Thanks you @Chris00!

**Comment by Chris00** [comment]
Upload to OPAM [pending](https://github.com/ocaml/opam-repository/pull/6412)...

**Comment by mmottl** [comment]
@Chris00 Thanks!
