### ISSUE TITLE
_oasis_remove_.ml and OASIS version of setup.ml

### ISSUE THREAD

**Issue by gildor478** [ocaml/oasis2opam#30]
Pre-emptive bug, I don't yet have the issue.

I see in commit 77b07e3b887f38ed387a8ca80d74cddf967d05fc, that you have removed the generation  of _oasis_remove_.ml (which is a good thing).

The problem is that '-C' is only fixed with OASIS 0.4.7 and you may have a setup.ml generated with former version (e.g. 0.4.6).

Can you check the version of OASIS used to generate setup.ml and issue an error if < 0.4.7 ?

To check the version
```
$ ocaml setup.ml -version
```

**Comment by Chris00** [comment]
Good remark.  Since I use the OASIS lib, I guess it is possible to have that info from the library, right?

**Comment by Chris00** [comment]
I could detect that because the `module Compat_0_4` is present, right?  At the moment, I do not execute anything from the tarball and I would like it to stay that way.

**Comment by gildor478** [comment]
No. This is embedded into one of the record field deep inside the auto-generated setup.ml.

This is actually unfortunate, because I know it would be useful to auto-extract it, without running setup.ml.

1. I think a quick fix for `oasis2opam` is to check with `ocaml setup.ml -version`.
2. You have unstructured data in setup.ml which reads like "Regenerated by OASIS (.*)" , but it is unstructured data, although you can probably easily extract it with a regex.
3.  l and I have created a [feature request](https://forge.ocamlcore.org/tracker/index.php?func=detail&aid=1715&group_id=54&atid=294) to implement what is needed (metadata in setup.ml) in the next version of OASIS.

**Comment by Chris00** [comment]
I used _2._ because I would prefer not to have to trust the setup.ml file. :-)
